version: "3.5"
services:
  # code:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .config:/home/coder/.config
  #     - $PWD:/home/coder/project
  #     - $(id -u):$(id -g)

  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
