version: "3.5"
services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-server
    environment:
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
    ports:
      - 8080:8443
    restart: unless-stopped
